# Generated by Django 5.0.6 on 2024-08-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Sigla', models.CharField(max_length=10)),
            ],
        ),
    ]
